### ISSUE TITLE
Smart Card Reader e.g. Insurance Company cards on Blazor hero

### ISSUE THREAD

**Issue by rjabuya** [blazorhero/CleanArchitecture#291]
Currently using Blazor hero template for my branch project to implement smart card reader functionality to allow detection of card number when swiped.

Anyone with any link to smart card reference contents, please share to add the functionality.

**Comment by iammukeshm** [comment]
Hi,

Sorry, this is a very specific requirement and cannot be incorporated into a general-purpose boilerplate template. Please use the discussions section for this.
